### ISSUE TITLE
Cholesky factorisation fails for inducing points

### ISSUE THREAD

**Issue by rossviljoen** [rossviljoen/SparseGPs.jl#1]
During optimisation of the parameters of `q(u|z)` (e.g. in `examples/gpflow_svgp.jl`), this cholesky factorisation often fails - even when not optimising inducing point locations`z`

https://github.com/rossviljoen/SparseGPs.jl/blob/3cec6a0935a483ebce5e5fea2b6e4e4729acf60a/src/svgp.jl#L5

with

`PosDefException: matrix is not positive definite; Cholesky factorization failed.`

**Comment by rossviljoen** [comment]
Just needed to add observation noise to `f(z)`

**Comment by theogf** [comment]
Just to mention, I wrote a package to automatically get a set of inducing points given some data: 
https://github.com/JuliaGaussianProcesses/InducingPoints.jl
which has a lot of flaws to be honest. But don't hesitate to try it and open issues eventually.
