### ISSUE TITLE
Quadrature (and Monte Carlo) for computing variational expectations

### ISSUE THREAD

**Issue by rossviljoen** [rossviljoen/SparseGPs.jl#3]
For many non-Gaussian likelihoods, the expectation in the first term in the ELBO `E_q(f) [ \log p(y|f) ]` from [1] has no closed form solution, so it needs to approximated somehow - typically by Gauss-Hermite quadrature, but possibly also via Monte Carlo. So, the planned approach for implementing this is:

- [x] An initial end-to-end working version of quadrature using [FastGaussQuadrature.jl](https://github.com/JuliaApproximation/FastGaussQuadrature.jl) with AD.
- [x] Compile a list of which non-Gaussian likelihoods have closed form solutions (probably by looking through GPFlow etc.)
- [x] Add support for MC methods.

[1] Hensman, James, Alexander Matthews, and Zoubin Ghahramani. "Scalable variational Gaussian process classification." Artificial Intelligence and Statistics. PMLR, 2015.

**Comment by theogf** [comment]
> Compile a list of which non-Gaussian likelihoods have closed form solutions (probably by looking through GPFlow etc.)

I am afraid that only works for the Gaussian likelihood :(

**Comment by rossviljoen** [comment]
Isn't it possible for some - e.g. for Gamma [here](https://github.com/GPflow/GPflow/blob/268e315fda816816f75580d5af51b58500f0447e/gpflow/likelihoods/scalar_continuous.py#L139)?

**Comment by st--** [comment]
> I am afraid that only works for the Gaussian likelihood :(

Closed-form *posterior* only for Gaussian likelihood, but closed-form `E_q(f)[ \log p(y|f) ]` exists for some other p(y|f) as well, as in the example Ross found.

**Comment by rossviljoen** [comment]
I have a working end-to-end example of classification in https://github.com/rossviljoen/SparseGPs.jl/blob/master/examples/classification.jl

**Comment by rossviljoen** [comment]
Implemented in #9
